name: Build .NET Core

on:
  push:
    branches:
      - develop
      - feature/compiler-v2-with-publish

env:
  MAIN_PROJECT: src/oscript/oscript.csproj
  SOLUTION: 1Script.sln

jobs: 
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        dotnet-version: [3.1.301]
        include:
          - os: windows-latest
            RID: win-x64
            target: netcoreapp3.1
            targetid:  net3.1
            testappbuild: dotnet publish -p:PublishTrimmed=true -f ${{ matrix.target }} -p:DebugType=None \
              -r ${{matrix.RID}}  -c Release --self-contained true --force \
              -p:IncludeNativeLibrariesInSingleFile=true -p:CopyOutputSymbolsToPublishDirectory=false \
              .\src\TestApp\TestApp.csproj -o distrs/${{matrix.targetid}}/${{matrix.RID}}/bin
          - os: ubuntu-latest
            RID: linux-x64
            target: netcoreapp3.1
            targetid:  net3.1
            testappbuild: echo TestApp only for windows
    defaults:
      run: 
        working-directory: .
    steps:

    # актуализация с сабмодулями
    - uses: actions/checkout@v2
      with: 
        submodules: true
    
    # установка дотнет
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    # публикация
    - name: BuildAndPublish
      run: dotnet clean src/oscript/oscript.csproj && \
        dotnet publish -p:PublishTrimmed=true -f ${{ matrix.target }} -p:DebugType=None \
          -r ${{matrix.RID}}  -c Release --self-contained true --force \
          -p:IncludeNativeLibrariesInSingleFile=true -p:CopyOutputSymbolsToPublishDirectory=false \
          ${{env.MAIN_PROJECT}} -o distrs/${{matrix.targetid}}/${{matrix.RID}}/bin

    # Заливка в артефакты
    - name: Artifact
      uses: actions/upload-artifact@v2
      with:
        name: oscript.v2-${{matrix.RID}}.zip
        path: distrs/${{matrix.targetid}}/${{matrix.RID}}
